version: "3.8"

services:
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgresql

  postgresql:
    image: postgres:13
    environment:
        - POSTGRES_USER=Bruna557
        - POSTGRES_PASSWORD=123456
        - POSTGRES_DB=ptw-challenge
    ports:
      - 5432:5432
